Adds for counters service
amalto/platform6-ui-components pull request #207
Opened 2020-11-04 18:00 UTC by vincentv

* move to lerna
* add react binding
* add p6-panel
* add p6-tab
* add p6-service-panel
* add p6-grid-row-actions
* add p6-file (Closes #159)

2020-11-04 18:17 UTC, choucrifahed requested changes

2020-11-04 18:17 UTC, choucrifahed commented on lerna-debug.log
> +0 silly argv   _: [ 'list' ],
Shouldn't a log file be ignored?

2020-11-04 18:17 UTC, choucrifahed commented on packages/core/readme.md
> +It is _important_ that your code is _consistant_, we use a _linter_ for that and have a few command lines.
consistent in English

2020-11-05 08:41 UTC, vuongc commented on packages/core/src/components/templates/p6-service-panel/locales/p6-service-panel.i18n.fr.json
> +  "restart": "Redémarre"
Redémarrer

2020-11-05 08:47 UTC, vuongc commented on packages/core/src/components/templates/p6-grid-row-actions/p6-grid-row-actions.tsx
> +function renderAction(action: Action, rowId: RowId, option: { disabled: boolean }): JSX.Element | null {
Why are those methods here ? They are part of the p6-grid-row-actions rendering. Is it to avoid to bind it to the actual context ?

2020-11-05 09:53 UTC, choucrifahed approved these changes

2020-11-05 10:38 UTC, vincentv commented on packages/core/src/components/templates/p6-grid-row-actions/p6-grid-row-actions.tsx
> +function renderAction(action: Action, rowId: RowId, option: { disabled: boolean }): JSX.Element | null {
These methods are not in the component because :
- there is no use case of **this** in it (Lint)
- anonymous functions are not recommended for events (Lint)

2020-11-05 14:14 UTC, vuongc commented on packages/core/src/components/templates/p6-grid-row-actions/p6-grid-row-actions.tsx
> +function renderAction(action: Action, rowId: RowId, option: { disabled: boolean }): JSX.Element | null {
Ok, fine for me

2020-11-05 14:14 UTC, merged